#!/bin/sh
if [ -a .commit ]
    then
    rm .commit
    git add $(git rev-parse --show-toplevel)/fme-sortable.coffee
    git add $(git rev-parse --show-toplevel)/spec/fme-sortable-spec.coffee
    git add $(git rev-parse --show-toplevel)/karma_tests.html
    git commit --amend -C HEAD --no-verify
fi
exit