engines:
  coffeelint:
    enabled: true
    config: .coffeelint.json
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.coffee"
  - "**.scss"
  - "**.js"
exclude_paths:
- node_modules/**/*
- coverage/**/*
- hook/**/*
- spec/**/*
- karma.conf.js
